address: key(ctrl-l)
go forward: key(alt-right)
go back: key(alt-left)
reload: key(ctrl-r)
reopen tab: key(ctrl-shift-t)
spring: key(ctrl-t)
crack: key(ctrl-w)

go first: key(ctrl-1)
go second: key(ctrl-2)
go third: key(ctrl-3)
go fourth: key(ctrl-4)
go fifth: key(ctrl-5)
go sixth: key(ctrl-6)
go seventh: key(ctrl-7)
go eighth: key(ctrl-8)
go ninth: key(ctrl-9)