gamer tag: "ZchryRbbt"
long gamer tag: "ZchryRbbit"

username: "nwu124"
Citrix username: "nathanielw"
middle name: "Rei Kan"
full name: "Nathaniel Wu"

Google email: "wu.nathaniel124@gmail.com"
school email: "nwu@seattleu.edu"
Microsoft email: "wu.nathaniel124@hotmail.com"
job email: "nathaniel.r.wu@gmail.com"
Citrix email: "nathaniel.wu@citrix.com"
Tibco email: "nwu@tibco.com"
cloud email: "Nathaniel.Wu@cloud.com"
gaming email: "zchryrbbt@gmail.com"
government email: "nathanielw@ctxgovops.us"
corps email: "Nathaniel.Wu@corp.cloud.com"

street address: "4671 Highland Drive"
postal code: "98006"
city: "Bellevue"
state: "WA"
phone number: "4252478098"
format phone number: "(425) 247-8098"
birthday: "091595"
long birthday: "09151995"

street: "St"
avenue: "Ave"
drive: "Dr"
north: "N"
northeast: "NE"
east: "E"
southeast: "SE"
south: "S"
southwest: "SW"
west: "W"
northwest: "NW"

LinkedIn address: "https://www.linkedin.com/in/nathaniel-r-wu/"
getter: "GitHub"
version: "git "
version fetch: "git fetch"
version pull: "git pull"
version checkout: "git checkout "
version cherry pick: "git cherry-pick "
version agent: "eval \"$(ssh-agent -s)\""
version load key: "ssh-add C:/Users/Nathaniel.Wu/.ssh/eddsa.ssh"
version reset soft: "git reset --soft "
version reset hard: "git reset --hard "
version rebase: "git rebase master"
version directory: "cd C:\\repos\\appmanagement"

build directory: "cd C:\\repos\\appmanagement"
build leasing service: ".\\buck build //geo_hub/services/internal/leasing_service/..."
build leasing sync service: ".\\buck build //geo_hub/services/internal/leasing_sync_service/..."
build root of trust: ".\\buck build //geo_hub/services/internal/root_of_trust/..."

greetings: "Hi "
laugh: "lol"
short laugh: "lol"
front laugh: " lol"
big curling: "URL"
curling: "url"
sequel: "SQL"
small Microsoft: "azure"
Microsoft: "Azure"
amazon: "AWS"
alone: "dedup"
pad alone: " dedup "
looking: "I see, "
unique: "GUID"
example: "e.g. "
federal: "FedRAMP"
government: "Gov"
broker prefix: "BRK-"
prefix: "XAC-"
kevlar prefix: "KVLR-"
acknowledged: "Got it, "
machine: "VDA"
machines: "VDAs"
artifact: "Artifactory"
upgrade: "VUS"
session: "SRS"
vacation: "PTO"
hundred: "00"
thousand: "000"
association: "HOA"
site reliability: "SREs"
pull request: "PR"
organization: "CVAD"
principal: "SPN"
gateway: "API-GW"
application: "API"
authentication: "Auth"
virtual: "VM"
line: "queue"
address prefix: "https://"
Europe: "EU"
pacific: "APS"
japan: "JP"
client: "CWA"
elastic: "EB"
instance: "EC2"
leasing: "LS"
sync service: "LSS"
root: "ROT"

signature: 
    "Thanks!"
    key(enter)
    "Nathaniel"

manager: "Saunil"
coworker one: "Mada"
coworker too: "Gulfam"
coworker three: "Akshay"

test customer: "n54zablj26da"
test address: "n54zablj26da.cloud.com"
test administrator: "n54zablj26da.local\\Administrator"

